services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pmblog
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
