// Type declarations for pagefind — a build-time static search library.
// The actual module is generated by `npx pagefind` after a production build
// and served from /pagefind/. It does not exist at compile time.
declare module "/pagefind/pagefind.js" {
  export function options(opts: Record<string, unknown>): Promise<void>;
  export function search(query: string): Promise<{
    results: Array<{
      data: () => Promise<{
        url: string;
        excerpt: string;
        meta: { title: string; [key: string]: string };
        [key: string]: unknown;
      }>;
    }>;
  }>;
}
